### ISSUE TITLE
New investigation: Failed to watch file...: no space left on device%

### ISSUE THREAD

**Issue by jnoller** [jnoller/kubernaughty#41]
Common failure where users using many watches - default settings may need to be tuned for specific workloads using daemonsets 

sysctl fs.inotify.max_user_watches 
fs.inotify.max_user_watches = 8192

Reset cap:

sysctl -w fs.inotify.max_user_watches=588576

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: more-fs-watchers
  namespace: kube-system
  labels:
    app: more-fs-watchers
spec:
  template:
    metadata:
      labels:
        name: more-fs-watchers
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      initContainers:
        - command:
            - sh
            - -c
            - sysctl -w fs.inotify.max_user_watches=524288;
          image: alpine:3.6
          imagePullPolicy: IfNotPresent
          name: sysctl
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys
              mountPath: /sys
      containers:
        - resources:
            requests:
              cpu: 0.01
          image: alpine:3.6
          name: sleepforever
          command: ["tail"]
          args: ["-f", "/dev/null"]
      volumes:
        - name: sys
          hostPath:
            path: /sys
```

this daemonset is an example: https://github.com/derekrprice/k8s-hacks/blob/master/systemd-cgroup-gc.yaml

this should be auto-reaped by the system
